### PR TITLE
Revert "More jiff"

### PR DESCRIPTION
**Pull request by jessekrubin**
Reverts jessekrubin/ry#118

### CODE REVIEW

**Comment by BurntSushi** [comment]
Did you run into problems with Jiff?

**Comment by jessekrubin** [comment]
Hello @BurntSushi,

I think the current jiff-wrapper is 90-95% of the way complete. I would love your thoughts on it. 

Thanks,
Jesse

**Comment by BurntSushi** [comment]
Hiya! I took a quick peak and... there is a lot of code! I'm not quite sure what I'm looking at to be honest. Are there any particular areas that you struggled with or aren't sure about?

**Comment by BurntSushi** [comment]
I think I probably just don't have the bandwidth to review this amount of code in a context that I'm pretty unfamiliar with (bridging Rust to Python is something I have zero experience with).

With that said:

* Types like `ZonedArithmetic`, `ZonedDifference`, `ZonedRound` and so on are basically just builders. In the Python ecosystem, it might be more idiomatic to use keyword args.
* I kind of feel like the type names should stay the same unless there is a specific conflict with something in the ecosystem. But naming is really hard and there are, I'm sure, competing concerns.
* Cloning `Zoned` and `TimeZone` seems fine to me. They are `Arc`s internally, so the cloning should be extremely cheap.

**Comment by jessekrubin** [comment]
@BurntSushi thanks so much for taking the time to answer my questions.

Do you mind if I start a discussion on this repo where I can ask you more questions if/when they pop up?

> I think I probably just don't have the bandwidth to review this amount of code in a context that I'm pretty unfamiliar with (bridging Rust to Python is something I have zero experience with).

It is a bunch of code and I don't think I fully knew what I was getting into when I started. If you do find the time, and play with it, I am very open to your feedback!
 
> * Types like `ZonedArithmetic`, `ZonedDifference`, `ZonedRound` and so on are basically just builders. In the Python ecosystem, it might be more idiomatic to use keyword args.

I just pr-ed in changes to use kwargs for `until`/`round`/`since`/etc. It is a good bit nicer to use. Several of the functions `until` have a sibling `_until` python method which only accepts a wrapper-ed version of the `Difference` struct which is a thing I have no memory of writing and think I was in a programming fugue-state. 

> * I kind of feel like the type names should stay the same unless there is a specific conflict with something in the ecosystem. But naming is really hard and there are, I'm sure, competing concerns.

I had them as `Zoned` and `Span` originally but a co-worker of mine thought that they were a bit ambiguous -- `Zoned` in particular given that we work in geospatial computing, but I can't think of another place where `Zoned` might be used. I am very tempted to change `ZonedDateTime` back to just `Zoned`. 

> * Cloning `Zoned` and `TimeZone` seems fine to me. They are `Arc`s internally, so the cloning should be extremely cheap.

Awesome! Some neurotic part of me feels terrible about using `clone()` -- I guess it is the same part of me that feels terrible about using `let` and not `const` in typescript...

**Comment by BurntSushi** [comment]
Yeah please do open a discussion or whatever. You can also ask questions on the Jiff tracker.

It occurs to me that one helpful thing would be to look at the [Temporal API](https://tc39.es/proposal-temporal/docs/). Temporal is principally what Jiff was inspired by. It occurs to me that Javascript and Python are much closer to each other than either are to Rust (thinking about exceptions and keyword arguments). So you'd probably have a better time trying to match the Javascript Temporal API than you do the Jiff crate. Jiff very nearly has complete Temporal functionality with the exception of non-Gregorian calendars and locale datetime formatting.

As for `Zoned` and `Span`, I think it depends on the context. If you see them as part of a datetime library, then I don't think they're ambiguous. Outside of that, sure, they could be. But when I create names, I usually think about them in the context of the crate in which they are defined.

**Comment by jessekrubin** [comment]
> Jiff very nearly has complete Temporal functionality with the exception of non-Gregorian calendars and locale datetime formatting.

That explains why my hebrew friend, Julian, told me that the ry-jiff api was giving him incorrect dates. 

I will start a sushi QA thread!

**Pull request closed without merging**
